### ISSUE TITLE
NPE in AdViewTimerTask

### ISSUE THREAD

**Issue by mvberg** [sharethrough/Android-SDK#34]
Stack below. Using latest release (v3.0) - any ideas? TY.

Error Report collected on : Mon Nov 09 07:20:00 PST 2015

Informations :
Locale: en_US
Version: 2.2.5
Package: com.barchart.app
Phone Model: SGH-T889
Android Version: 4.3
Board: smdk4x12
Brand: samsung
Device: t0ltetmo
Host: SWDB4808
ID: JSS15J
Model: SGH-T889
Product: t0ltetmo
Type: user
Total Internal memory: 11881627648
Available Internal memory: 1254268928

Stack:
java.lang.NullPointerException
at android.view.View.getGlobalVisibleRect(View.java:10892)
at android.view.View.getGlobalVisibleRect(View.java:10898)
at com.sharethrough.sdk.AdViewTimerTask.is80PercentOfAdIsOffScreen(AdViewTimerTask.java:115)
at com.sharethrough.sdk.AdViewTimerTask.checkIfOffScreen(AdViewTimerTask.java:95)
at com.sharethrough.sdk.AdViewTimerTask.fireVisibilityEventsWhenAppropriate(AdViewTimerTask.java:75)
at com.sharethrough.sdk.AdViewTimerTask.run(AdViewTimerTask.java:110)
at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by mvberg** [comment]
Closing, failed to repo again.
