### ISSUE TITLE
Race condition in AdvertisingIdProvider

### ISSUE THREAD

**Issue by davidgouldsky** [sharethrough/Android-SDK#53]
If you're app is slow to load up after Sharethrough has been initialised, you can get the following exception stack trace:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.ads.identifier.AdvertisingIdClient$Info.getId()' on a null object reference
                                                                                                    at com.sharethrough.sdk.AdvertisingIdProvider$1.run(AdvertisingIdProvider.java:32)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                    at java.lang.Thread.run(Thread.java:761)

Consider handling the NullPointerException and re-attempting the load.

**Comment by dshei** [comment]
Thanks David, added the null check
